Use U32 and U8 instead of LONG and BYTE.  LONG and BYTE was in conflict with some Win32 stuff.
> nmake -> 1 error
-------
SHA1.c
SHA1.xs(24) : error C2371: 'LONG' : redefinition; different basic types
        E:\VStudio\VC98\INCLUDE\winnt.h(136) : see declaration of 'LONG'

header file: winnt.h
--------------------
132 #ifndef VOID
133 #define VOID void
134 typedef char CHAR;
135 typedef short SHORT;
136 typedef long LONG;
137 #endif